require("gitsigns").setup({
  on_attach = function(buf)
    local gs = require("gitsigns")
    vim.keymap.set("n", "]h", gs.next_hunk, { buffer = buf, desc = "Next hunk" })
    vim.keymap.set("n", "[h", gs.prev_hunk, { buffer = buf, desc = "Prev hunk" })
    vim.keymap.set("n", "<leader>gs", gs.stage_hunk, { buffer = buf, desc = "Stage hunk" })
    vim.keymap.set("n", "<leader>gr", gs.reset_hunk, { buffer = buf, desc = "Reset hunk" })
    vim.keymap.set("n", "<leader>gu", gs.undo_stage_hunk, { buffer = buf, desc = "Undo stage hunk" })
    vim.keymap.set("n", "<leader>gp", gs.preview_hunk, { buffer = buf, desc = "Preview hunk" })
    vim.keymap.set("n", "<leader>gb", gs.blame_line, { buffer = buf, desc = "Blame line" })
    vim.keymap.set("v", "<leader>gs", function()
      gs.stage_hunk({ vim.fn.line("."), vim.fn.line("v") })
    end, { buffer = buf, desc = "Stage selection" })
    vim.keymap.set("v", "<leader>gr", function()
      gs.reset_hunk({ vim.fn.line("."), vim.fn.line("v") })
    end, { buffer = buf, desc = "Reset selection" })
  end,
})
